### ISSUE TITLE
Error loading images

### ISSUE THREAD

**Issue by mostlyjason** [reactioncommerce/reaction-devtools#19]
When I click the "Load Images" button in the dev tools I get the below error message in my logs. I tried resetting the data and loading again and got same error. The other buttons work fine.

Exception while invoking method 'devtools/loaddata/images' Error: Match error: Expected string, got undefined
] at check (packages/check/match.js:35:15)
] at MethodInvocation.methods.loadImages (imports/plugins/custom/reaction-devtools/server/methods.js:538:3)
] at packages/check/match.js:108:16
] at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
] at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
] at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
] at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
] at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
] at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
] at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
] at Promise (packages/ddp-server/livedata_server.js:715:46)
] at new Promise (<anonymous>)
] at Session.method (packages/ddp-server/livedata_server.js:689:23)
] at packages/ddp-server/livedata_server.js:559:43
] Sanitized and reported to the client as: Match failed [400]
]

**Comment by loan-laux** [comment]
Should be fixed with the latest release @mostlyjason. Can you try again and confirm?
